_os_overrides_:
  linux:
    compiler_bin_url: ''
  macos:
    compiler_bin_url: ''
  win:
    compiler_bin_url: ''
_required_fields_: ''
artefact_type: ''
compiler_bin_url: ''
libs: ''
name: ''
org: ''
platform: terminal
repo: ''
version: ''